import { TierNames } from "../typescript/enums";
import type { AICardCharacteristics, AICardCharacteristicsArray, AllBasicHeroesPossibleCardId, AllCoinsValue, AllDwarfPlayersAmountId, AllDwarfPointsValuesArraysLength, AllHeroesForDifficultySoloModePossibleCardId, AllHeroesForPlayerOrSoloBotAddToPlayerBoardPossibleCardId, AllHeroesForPlayerSoloModeAndvariPossibleCardId, AllHeroesForPlayerSoloModePossibleCardId, AllHeroesForSoloBotAndvariPossibleCardId, AllHeroesForSoloBotPossibleCardId, AllHeroesPossibleCardId, AllInitialCoins, AllInitialTradingCoinConfig, AllPriorityValue, AllRoyalCoinConfig, BasicVidofnirVedrfolnirUpgradeValue, BettermentMinMax, CampCard, CampCardArray, CampCardArrayIndex, CanBeNegativeDwarfCardPoints, CanBeNull, CanBeUndef, Coin, CoinUpgradePossibleMaxValue, CoinsOnPouchNumber, Ctx, CurrentPlayerCoinsScore, DistinctionsPlayersOrderArray, DwarfDeckCard, DwarfPointsValues, DwergBrothersScoringArray, ExchangeOrderArray, ExplorerDistinctionCardId, ExplorerDistinctionCards, GeneralStrategyForSoloBotAndvariId, HeroCard, HeroesForSoloGameArray, HeroesForSoloGameDifficultyLevelArray, HeroesForSoloGameForStrategyBotAndvariArray, HeroesInitialForSoloGameForBotAndvariArray, IndexOf, InitialCoin, MarketCoinNumberValues, MaxCurrentSuitDistinctionPlayersArray, MaxPlyersWithTotalScore, MercenariesConfigArray, MinerDistinctionsScoring, MythologicalCreatureCard, MythologicalCreatureCardsForGiantSkymirArray, MythologicalCreatureDeckForSkymirCardId, OneOrTwo, PlayerCoinId, PlayerCoinNumberValues, PlayerCoinsNumber, PlayerID, PlayerIndex, PlayerPouchCoinId, PlayerRanksForDistinctionsArray, PlayerStack, PlayerTavernCoinId, PlayoutDepth, PrioritiesAmount, PrioritiesForPlayerNumbers, Priority, PrivatePlayerBoardCoins, PrivatePlayerHandCoins, PublicPlayerBoardCoins, PublicPlayerCoin, PublicPlayerHandCoins, PublicPlayersOrderArray, RandomPriorityIndex, RefillDeckCardsWithExpansionArray, RefillDeckCardsWithoutExpansionArray, RemovedCardsFromTavernArray, ReserveStrategyForSoloBotAndvariId, ResolvedPlayersOrderArray, RoyalCoin, RoyalCoinValue, RoyalCoinsUniqueArray, RoyalOfferingsConfig, SecretAllCampDecks, SecretAllDwarfDecksArray, SecretAllDwarfDecksArrayIndex, SoloGameAndvariStrategyVariantLevel, SoloGameDifficultyLevelArg, Stack, StrengthTokenNotchLongMax, StrengthTokenNotchShortMax, TavernAllCardsArray, TavernCard, TavernPossibleCardId, TavernsArrayIndex, TavernsHeuristicArray, TotalScoreArray, TradingCoins, TradingCoinsValue, UpgradableCoin, UpgradableCoinValue, UpgradingCoinsArray, VidofnirVedrfolnirCoinsValue, WinnerArray, WinnersNum, ZeroOrOne } from "../typescript/interfaces";
export declare function AssertPlayoutDepth(ctx: Ctx, number: number): asserts number is PlayoutDepth;
export declare function AssertPrioritiesForPlayerNumbers(ctx: Ctx, prioritiesArray: Priority[]): asserts prioritiesArray is PrioritiesForPlayerNumbers;
export declare function AssertRandomPriorityIndex(ctx: Ctx, number: number): asserts number is RandomPriorityIndex;
export declare function AssertPlayerId(ctx: Ctx, playerID: string): asserts playerID is PlayerID;
export declare function AssertPlayerIndex(ctx: Ctx, number: number): asserts number is PlayerIndex;
export declare function AssertZeroOrOne(number: number): asserts number is ZeroOrOne;
export declare function AssertOneOrTwo(number: number): asserts number is OneOrTwo;
export declare function AssertSoloGameAndvariStrategyVariantLevel(number: number): asserts number is SoloGameAndvariStrategyVariantLevel;
export declare function AssertAllHeroesForPlayerOrSoloBotAddToPlayerBoardPossibleCardId(number: number): asserts number is AllHeroesForPlayerOrSoloBotAddToPlayerBoardPossibleCardId;
export declare function AssertSoloGameDifficultyLevelArg(number: number): asserts number is SoloGameDifficultyLevelArg;
export declare function AssertMinerDistinctionsScoring(number: number): asserts number is MinerDistinctionsScoring;
export declare function AssertBasicVidofnirVedrfolnirUpgradeValue(number: number): asserts number is BasicVidofnirVedrfolnirUpgradeValue;
export declare function AssertBettermentMinMax(number: number): asserts number is BettermentMinMax;
export declare function AssertCanBeNegativeDwarfCardPoints(number: number): asserts number is CanBeNegativeDwarfCardPoints;
export declare function AssertDwarfPointsArrayValues(number: number): asserts number is DwarfPointsValues;
export declare function AssertCoinUpgradePossibleMaxValue(number: number): asserts number is CoinUpgradePossibleMaxValue;
export declare function AssertMythologicalCreatureDeckForSkymirCardId(number: number): asserts number is MythologicalCreatureDeckForSkymirCardId;
export declare function AssertAllHeroesPossibleCardId(heroId: number): asserts heroId is AllHeroesPossibleCardId;
export declare function AssertAllBasicHeroesPossibleCardId(heroId: number): asserts heroId is AllBasicHeroesPossibleCardId;
export declare function AssertAllHeroesForPlayerSoloModePossibleCardId(heroId: number): asserts heroId is AllHeroesForPlayerSoloModePossibleCardId;
export declare function AssertAllHeroesForPlayerSoloModeAndvariPossibleCardId(heroId: number): asserts heroId is AllHeroesForPlayerSoloModeAndvariPossibleCardId;
export declare function AssertAllHeroesForSoloBotPossibleCardId(heroId: number): asserts heroId is AllHeroesForSoloBotPossibleCardId;
export declare function AssertAllHeroesForSoloBotAndvariPossibleCardId(heroId: number): asserts heroId is AllHeroesForSoloBotAndvariPossibleCardId;
export declare function AssertAllHeroesForDifficultySoloModePossibleCardId(heroId: number): asserts heroId is AllHeroesForDifficultySoloModePossibleCardId;
export declare function AssertExplorerDistinctionCardId(number: number): asserts number is ExplorerDistinctionCardId;
export declare function AssertMarketCoinNumberValues(number: number): asserts number is MarketCoinNumberValues;
export declare function AssertPlayerCoinNumberValues(number: number): asserts number is PlayerCoinNumberValues;
export declare function AssertTavernCardId(number: number): asserts number is TavernPossibleCardId;
export declare function AssertPlayerTavernCoinId(number: number): asserts number is PlayerTavernCoinId;
export declare function AssertGeneralStrategyForSoloBotAndvariId(number: number): asserts number is GeneralStrategyForSoloBotAndvariId;
export declare function AssertReserveStrategyForSoloBotAndvariId(number: number): asserts number is ReserveStrategyForSoloBotAndvariId;
export declare function AssertPlayerCoinsNumber(number: number): asserts number is PlayerCoinsNumber;
export declare function AssertCurrentPlayerCoinsScore(number: number): asserts number is CurrentPlayerCoinsScore;
export declare function AssertVidofnirVedrfolnirCoinsValue(number: number): asserts number is VidofnirVedrfolnirCoinsValue;
export declare function AssertMaxPlyersWithTotalScore(number: number): asserts number is MaxPlyersWithTotalScore;
export declare function AssertWinnersNum(number: number): asserts number is WinnersNum;
export declare function AssertCoinsOnPouchNumber(number: number): asserts number is CoinsOnPouchNumber;
export declare function AssertStrengthTokenNotchShortMax(number: number): asserts number is StrengthTokenNotchShortMax;
export declare function AssertAllDwarfPlayersAmountId(number: number): asserts number is AllDwarfPlayersAmountId;
export declare function AssertStrengthTokenNotchLongMax(number: number): asserts number is StrengthTokenNotchLongMax;
export declare function AssertPrioritiesAmount(number: number): asserts number is PrioritiesAmount;
export declare function AssertRoyalCoinValue(number: number): asserts number is RoyalCoinValue;
export declare function AssertAllPriorityValue(number: number): asserts number is AllPriorityValue;
export declare function AssertAllCoinsValue(number: number): asserts number is AllCoinsValue;
export declare function AssertUpgradableCoinValue(number: number): asserts number is UpgradableCoinValue;
export declare function AssertPlayerCoinId(number: number): asserts number is PlayerCoinId;
export declare function AssertPlayerPouchCoinId(number: number): asserts number is PlayerPouchCoinId;
export declare function AssertAllNumberValuesArraysLength(number: number): asserts number is AllDwarfPointsValuesArraysLength;
export declare function AssertSecretAllDwarfDecksArrayIndex(number: number): asserts number is SecretAllDwarfDecksArrayIndex;
export declare function AssertHeroesForSoloGameForStrategyBotAndvariIndex(number: number): asserts number is IndexOf<HeroesForSoloGameForStrategyBotAndvariArray>;
export declare function AssertDwergBrothersScoringArrayIndex(number: number): asserts number is IndexOf<DwergBrothersScoringArray>;
export declare function AssertSecretAllDwarfDecksIndex(number: number): asserts number is IndexOf<SecretAllDwarfDecksArray>;
export declare function AssertSecretAllCampDecksIndex(number: number): asserts number is IndexOf<SecretAllCampDecks>;
export declare function AssertCampIndex(number: number): asserts number is CampCardArrayIndex;
export declare function AssertTavernIndex(number: number): asserts number is TavernsArrayIndex;
export declare function AssertTavernsHeuristicArrayIndex(number: number): asserts number is IndexOf<TavernsHeuristicArray>;
export declare function AssertMercenariesConfigIndex(number: number): asserts number is IndexOf<MercenariesConfigArray>;
export declare function AssertRoyalOfferingsConfigIndex(number: number): asserts number is IndexOf<RoyalOfferingsConfig>;
export declare function AssertTierIndex(number: number): asserts number is TierNames;
export declare function AssertAllInitialTradingCoinConfigIndex(number: number): asserts number is IndexOf<AllInitialTradingCoinConfig>;
export declare function AssertAllRoyalCoinConfigIndex(number: number): asserts number is IndexOf<AllRoyalCoinConfig>;
export declare function AssertRoyalCoinsUniqueArrayIndex(number: number): asserts number is IndexOf<RoyalCoinsUniqueArray>;
export declare function AssertAICardCharacteristicsArrayIndex(number: number): asserts number is IndexOf<AICardCharacteristicsArray>;
export declare function AssertTop1And2ScoreNumber(top1And2ScoreNumber: CanBeUndef<number>): asserts top1And2ScoreNumber is number;
export declare function AssertTavernAllCardsArray(tavernAllCardsArray: TavernCard[]): asserts tavernAllCardsArray is TavernAllCardsArray;
export declare function AssertHeroesForSoloGameDifficultyLevelArray(heroesForSoloGameDifficultyLevelArray: readonly HeroCard[]): asserts heroesForSoloGameDifficultyLevelArray is HeroesForSoloGameDifficultyLevelArray;
export declare function AssertRefillDeckCardsWithExpansionArray(refillDeckCardsWithExpansionArray: MythologicalCreatureCard[]): asserts refillDeckCardsWithExpansionArray is RefillDeckCardsWithExpansionArray;
export declare function AssertRemovedCardsFromTavernArray(removedCardsFromTavernArray: TavernCard[]): asserts removedCardsFromTavernArray is RemovedCardsFromTavernArray;
export declare function AssertRefillDeckCardsWithoutExpansionArray(refillDeckCardsWithoutExpansionArray: DwarfDeckCard[]): asserts refillDeckCardsWithoutExpansionArray is RefillDeckCardsWithoutExpansionArray;
export declare function AssertMaxCurrentSuitDistinctionPlayersArray(maxCurrentSuitDistinctionPlayersArray: PlayerID[]): asserts maxCurrentSuitDistinctionPlayersArray is MaxCurrentSuitDistinctionPlayersArray;
export declare function AssertExchangeOrderArray(exchangeOrderArray: PlayerID[]): asserts exchangeOrderArray is ExchangeOrderArray;
export declare function AssertResolvedPlayersOrderArray(resolvedPlayersOrderArray: PlayerID[]): asserts resolvedPlayersOrderArray is ResolvedPlayersOrderArray;
export declare function AssertPublicPlayersOrderArray(publicPlayersOrderArray: PlayerID[]): asserts publicPlayersOrderArray is PublicPlayersOrderArray;
export declare function AssertDistinctionsPlayersOrderArray(distinctionsPlayersOrderArray: PlayerID[]): asserts distinctionsPlayersOrderArray is DistinctionsPlayersOrderArray;
export declare function AssertPlayerRanksForDistinctionsArray(playerRanksForDistinctionsArray: readonly number[]): asserts playerRanksForDistinctionsArray is PlayerRanksForDistinctionsArray;
export declare function AssertTotalScoreArray(totalScoreArray: number[]): asserts totalScoreArray is TotalScoreArray;
export declare function AssertWinnerArray(winnerArray: PlayerID[]): asserts winnerArray is WinnerArray;
export declare function AssertUpgradingCoinsArray(upgradingCoinsArray: readonly UpgradableCoin[]): asserts upgradingCoinsArray is UpgradingCoinsArray;
export declare function AssertAICardCharacteristicsArray(aiCardCharacteristicsArray: readonly AICardCharacteristics[]): asserts aiCardCharacteristicsArray is AICardCharacteristicsArray;
export declare function AssertTavernsHeuristicArray(tavernsHeuristicArray: number[]): asserts tavernsHeuristicArray is TavernsHeuristicArray;
export declare function AssertHandCoins(handCoins: PublicPlayerCoin[]): asserts handCoins is PublicPlayerHandCoins;
export declare function AssertPrivateBoardCoins(boardCoins: Coin[]): asserts boardCoins is PrivatePlayerBoardCoins;
export declare function AssertPrivateHandCoins(handCoins: Coin[]): asserts handCoins is PrivatePlayerHandCoins;
export declare function AssertRoyalCoinsUnique(uniqueRoyalCoins: RoyalCoin[]): asserts uniqueRoyalCoins is RoyalCoinsUniqueArray;
export declare function AssertBoardCoins(boardCoins: PublicPlayerCoin[]): asserts boardCoins is PublicPlayerBoardCoins;
export declare function AssertInitialCoins(initialCoins: readonly InitialCoin[]): asserts initialCoins is AllInitialCoins;
export declare function AssertFullMythologicalCreatureCardsForGiantSkymir(mythologyCreatureCardsSkymir: MythologicalCreatureCard[]): asserts mythologyCreatureCardsSkymir is MythologicalCreatureCardsForGiantSkymirArray;
export declare function AssertTradingCoins(tradingCoins: readonly UpgradableCoin[]): asserts tradingCoins is TradingCoins;
export declare function AssertTradingCoinsValues(tradingCoinsValues: readonly number[]): asserts tradingCoinsValues is TradingCoinsValue;
export declare function AssertExplorerDistinctionCards(explorerDistinctionCards: readonly DwarfDeckCard[]): asserts explorerDistinctionCards is ExplorerDistinctionCards;
export declare function AssertCamp(camp: CanBeNull<CampCard>[]): asserts camp is CampCardArray;
export declare function AssertHeroesForSoloBot(heroesForSoloBot: readonly HeroCard[]): asserts heroesForSoloBot is HeroesForSoloGameArray;
export declare function AssertHeroesInitialForSoloGameForBotAndvari(heroesInitialForSoloGameForBotAndvari: readonly HeroCard[]): asserts heroesInitialForSoloGameForBotAndvari is HeroesInitialForSoloGameForBotAndvariArray;
export declare function AssertHeroesForSoloGameForStrategyBotAndvari(heroesForSoloGameForStrategyBotAndvari: readonly HeroCard[]): asserts heroesForSoloGameForStrategyBotAndvari is HeroesForSoloGameForStrategyBotAndvariArray;
export declare function AssertPlayerStack(stack: Stack | PlayerStack): asserts stack is PlayerStack;
//# sourceMappingURL=AssertionTypeHelpers.d.ts.map